name: "Release"

on:
  push:
    branches:
      - "master"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Release
        uses: Porostik/release-action@debug
        with:
          api_token: ${{ secrets.api_token }}
          pull_name: ${{ github.event.pull_request.title }}
