name: "Release"

on:
  push:
    branches:
      - "master"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1
      - name: Release
        uses: Porostik/release-action@master
        with:
          api_token: ${{ secrets.api_token }}
